version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysqlcontainer
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
    networks:
      - cashbycard-compose-network

  cashbycard:
    build:
        context: .
        dockerfile: Dockerfile
    image: cashbycard
    environment:
        MYSQL_CONNECTION_STRING: "tcp(localhost:3306)/cashbycard?charset=utf8&parseTime=True&loc=Local"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "password"
    container_name: cashbycard
    command: /bin/bash
    tty: true
    ports:
        - 3000:3000
    volumes:
        - .:/cashbycard
    depends_on:
        - mysql
    external_links:
        - mysqlsrv
    networks:
        - cashbycard-compose-network

networks:
  cashbycard-compose-network:
      driver: bridge