services:
  mysql:
    image: mysql:5.7
    container_name: mysqlcontainer
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_cashbycard_data:/var/lib/mysql
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - cashbycard-compose-network

networks:
  cashbycard-compose-network:
    driver: bridge

volumes:
  mysql_cashbycard_data:
    name: mysql_cashbycard_data
